### ISSUE TITLE
Migration is failing continue...

### ISSUE THREAD

**Issue by clawes** [savannabits/charaza-ui#10]
php artisan migrate is failing.  It's try to add a column that already exists.

Migrating: 2020_11_19_170823_add_profile_photo_path_field_to_users

   Illuminate\Database\QueryException

  SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'profile_photo_path' (SQL: alter table `users` add `profile_photo_path` varchar(255) null)

**Comment by coolsam726** [comment]
I think when I created the project I was using a starter database dump which already contained all those fields. I will refactor the migrations so that migrations can run without any starter dump.

**Comment by coolsam726** [comment]
To solve the migration issue, when you create a new project first of all restore the dump located at `docker-compose/mysql/init_db.sql` into your database, then run `php artisan migrate`
