### ISSUE TITLE
Access forbidden

### ISSUE THREAD

**Issue by clawes** [savannabits/charaza-ui#11]
I logged in using the admin account but getting 403 Forbidden when accessing  /admin/articles
E.g. http://localhost:8000/admin/articles

**Comment by coolsam726** [comment]
Could be that the role assignment did not work? Do you have access to manage roles and permissions?

**Comment by coolsam726** [comment]
Hi, I am closing this hoping your permissions issue was resolved.
If your issue was not solved please feel free to reopen it.
