### ISSUE TITLE
Migration is failing

### ISSUE THREAD

**Issue by clawes** [savannabits/charaza-ui#9]
php artisan migrate is failing due to missing columns in the users table.
- Output 
....
Migrated:  2020_07_24_114250_create_permission_tables (342.79ms)
Migrating: 2020_08_01_094733_seed_administrator_role_and_user

   Illuminate\Database\QueryException

  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'username' in 'field list' (SQL: insert into `users` (`username`, `email`, `name`, `first_name`, `last_name`, `password`, `created_at`, `updated_at`) values (administrator, admin@savannabits.com, System Admin, System, Admin, $2y$10$7S52EY.IRugShIVC4Z/ZV.EqyB.oKuhNzpK5F3/khc6wepQEskuAW, 2021-03-01 04:43:30, 2021-03-01 04:43:30))

The users table is missing the username, first_name, and last_name columns.

**Comment by coolsam726** [comment]
Take a look at [This Solution](https://github.com/savannabits/charaza-ui/issues/10#issuecomment-855677902) and see if it can help you. We will make the package more independent in terms of the database migrations in future. (Less opinionated).
